"""empty message

Revision ID: 8979c6787ca8
Revises: 26564b599a50
Create Date: 2025-04-22 15:49:23.396582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8979c6787ca8'
down_revision = '26564b599a50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('naves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('cargo_capacity', sa.String(length=50), nullable=False),
    sa.Column('crew', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relacion_user_nave',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nave_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nave_id'], ['naves.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'nave_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relacion_user_nave')
    op.drop_table('naves')
    # ### end Alembic commands ###
